version: "3.9"

services:
  nuxt:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: pnpm run dev

  nuxt-prod:
    build:
      context: .
      target: build
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    command: pnpm run preview
