// @ts-check
import withNuxt from "./.nuxt/eslint.config.mjs"

export default withNuxt({
    files: ["**/*.{js,mjs,cjs,ts,vue}"],
    rules: {
        "vue/multi-word-component-names": "off",
        "no-compare-neg-zero": ["error", "always"],
        "no-cond-assign": ["error", "always"],
        "no-console": "warn",
        "no-constant-condition": "warn",
        "no-control-regex": "warn",
        "no-debugger": "warn",
        "no-dupe-args": "error",
        "no-dupe-keys": "error",
        "no-duplicate-case": "error",
        "no-empty": "warn",
        "no-empty-character-class": "warn",
        "no-ex-assign": "error",
        "no-extra-boolean-cast": "warn",
        "no-extra-semi": "warn",
        "no-func-assign": "error",
        "no-inner-declarations": "error",
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": "warn",
        "no-obj-calls": "error",
        "no-regex-spaces": "warn",
        "no-sparse-arrays": "warn",
        "no-unexpected-multiline": "warn",
        "no-unreachable": "warn",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": "error",
        "use-isnan": "error",
        "valid-typeof": "error",
        "no-case-declarations": "error",
        "no-empty-pattern": "error",
        "no-fallthrough": "error",
        "no-global-assign": "error",
        "no-octal": "error",
        "no-redeclare": "error",
        "no-self-assign": "error",
        "no-unused-labels": "error",
        "no-useless-catch": "error",
        "no-useless-escape": "error",
        "no-delete-var": "error",
        "no-undef": "error",
        "no-unused-vars": "warn",
        "no-mixed-spaces-and-tabs": "warn",
        "constructor-super": "error",
        "no-class-assign": "error",
        "no-const-assign": "error",
        "no-dupe-class-members": "error",
        "no-new-symbol": "error",
        "no-this-before-super": "error",
        "require-yield": "error",
    }
});
